library:
  source-dirs: src
tests:
  TwitterBotHS-test:
    source-dirs: test
    main: Spec.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - TwitterBotHS
copyright: 2019 lnsf
maintainer: lnsf03@gmail.com
dependencies:
- mtl
- postgresql-simple
- yaml
- random
- http-types
- split
- base >= 4.7 && < 5
- mecab
- http-conduit
- authenticate-oauth
- aeson
- bytestring
- text
name: TwitterBotHS
version: 0.1.0.0
extra-source-files:
- README.md
- ChangeLog.md
author: lnsf
github: lnsf/DBTwitterBot
license: BSD3
executables:
  tbot-rep:
    main: app/MainRep.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mtl
    - TwitterBotHS
  tbot:
    main: app/Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mtl
    - TwitterBotHS
description: Please see the README on GitHub at <https://github.com/lnsf/DBTwitterBot#readme>
